### ISSUE TITLE
load libiojava.a error

### ISSUE THREAD

**Issue by kenvifire** [kenvifire/io.java#3]
libiojava.a: unknown file type, first eight bytes: 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1833)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1709)

**Comment by kenvifire** [comment]
Maybe wrong option in xcode build settings.

**Comment by kenvifire** [comment]
fixed, recreate CMakeList file

**Comment by kenvifire** [comment]
Fixed by making libiojava as a shared libaray.
